### ISSUE TITLE
validateCssUnit??? 

### ISSUE THREAD

**Issue by shilohfling** [erikpal/WUschedule#1]
After changing the layout of the app on server.R, I'm getting the error message: "Error in validateCssUnit: CSS units must be a single-element numeric or character vector"

I've tried searching around for how to trouble shoot this, but there's hardly information on it. Additionally, I did not get this error message with the other shiny app where I used this exact same layout.

**Comment by erikpal** [comment]
Just a problem with parenthesis after you moved the items around.
